CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY,
    type VARCHAR(10) NOT NULL,
    title VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    event_time TIMESTAMP WITH TIME ZONE NOT NULL,
    done BOOLEAN DEFAULT FALSE,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);